[package]
name = "rlox"
version = "0.1.0"
authors = ["Grisha Kruglov <gkruglov@mozilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
text_io = "0.1.9"
lazy_static = "1.4.0"